# Generated by Django 5.2.17 on 2026-09-09 16:01

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_plate', models.CharField(max_length=50)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rider_profiles',
            },
        ),
    ]
