# Generated by Django 5.2.17 on 2026-09-09 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlipTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trans_ref', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sending_bank', models.CharField(blank=True, max_length=20, null=True)),
                ('receiving_bank', models.CharField(blank=True, max_length=20, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slip_image_url', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(default=dict)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='slip_transactions', to='orders.order')),
            ],
            options={
                'db_table': 'slip_transactions',
                'ordering': ['-verified_at'],
            },
        ),
    ]
