import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0001_initial')]
    operations = [
        migrations.CreateModel(name='CustomerProfile', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('default_delivery_address', models.TextField()), ('delivery_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)), ('delivery_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)), ('registered_at', models.DateTimeField(auto_now_add=True)), ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL))], options={'db_table': 'customer_profiles'}),
        migrations.CreateModel(name='MerchantApplication', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('store_name', models.CharField(max_length=255)), ('phone_number', models.CharField(max_length=20)), ('address', models.TextField()), ('latitude', models.DecimalField(decimal_places=7, max_digits=10)), ('longitude', models.DecimalField(decimal_places=7, max_digits=10)), ('storefront_image', models.ImageField(upload_to='merchant-applications/storefronts/')), ('identity_document', models.FileField(blank=True, null=True, upload_to='merchant-applications/identity/')), ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)), ('admin_note', models.TextField(blank=True, null=True)), ('submitted_at', models.DateTimeField(blank=True, null=True)), ('reviewed_at', models.DateTimeField(blank=True, null=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_application', to=settings.AUTH_USER_MODEL))], options={'db_table': 'merchant_applications'}),
        migrations.CreateModel(name='RiderApplication', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('full_name', models.CharField(max_length=255)), ('phone_number', models.CharField(max_length=20)), ('vehicle_plate', models.CharField(max_length=50)), ('driver_license_image', models.ImageField(upload_to='rider-applications/licenses/')), ('vehicle_image', models.ImageField(upload_to='rider-applications/vehicles/')), ('additional_document', models.FileField(blank=True, null=True, upload_to='rider-applications/documents/')), ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)), ('admin_note', models.TextField(blank=True, null=True)), ('submitted_at', models.DateTimeField(blank=True, null=True)), ('reviewed_at', models.DateTimeField(blank=True, null=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_application', to=settings.AUTH_USER_MODEL))], options={'db_table': 'rider_applications'}),
    ]
